version: '3.8'

services:
  postgres:
    image: postgres:16.1
    container_name: postgres_db
    environment:
      POSTGRES_USER: nattkarn
      POSTGRES_PASSWORD: Arm@1144nb
      POSTGRES_DB: db_nestjs_passport_2025
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
